### ISSUE TITLE
How to convert curl data-binary into HTTP body in react native fetch?

### ISSUE THREAD

**Issue by ykcadcg** [ibm-cloud-docs/speech-to-text#209]
I followed IBM documentation https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-http#HTTP-basic  and was able to get results via `curl -X POST -u "apikey:x" --header "Content-Type: audio/flac" --data-binary @/Users/xx/Downloads/audio-file.flac  "https://apixxx" `.

But in react native below would give error "400 Bad Request error: Stream was 36 bytes but needs to be at least 100 bytes." --apparently it took the "body" I put as a string not a binary. How to fix it please? Thanks!
```
 window.btoa = require('Base64').btoa;
    let result = await fetch(
      'https://apixxx' , {
        method: 'POST',
        headers: {
          'Content-Type': 'audio/flac',
          'Authorization': 'Basic '+btoa(`apikey:x`)
        },
        body: JSON.stringify({
          'data-binary': '@./audio-file.flac',
        }),
      }
    ).then(response => response.json());
```
I then tried another version with formdata, gives error: "Bad Request", code: 400, error: "No JSON object could be decoded"
```
    window.btoa = require('Base64').btoa;
      const formData = new FormData()
      formData.append('file', {
        uri: `file://${RNFS.DocumentDirectoryPath}/audio-file.flac`,
        name: 'audio-file.flac',
        type: 'audio/flac',
      })
        let res = await fetch('https://apixxx', {
            method: 'POST',
            headers: {
              'Content-Type': 'multipart/form-data',
              'Authorization': 'Basic '+btoa(`apikey:x`),
            },
            body: formData,
          }).then(response => console.log(response.json()));
```
How to fix it please? Thanks!

**Comment by jeffpk62** [comment]
React is not part of the documented API reference, but there is a github page of information that may help you:  https://github.com/watson-developer-cloud/speech-to-text-code-pattern.  I hope you find this page useful, and I apologize for the very late response.
