### ISSUE TITLE
ABNF Grammar examples in some pages are not working

### ISSUE THREAD

**Issue by bobfang** [ibm-cloud-docs/speech-to-text#214]
On the documentation page:
https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-grammarUnderstand#yesnoGrammar

```
# ABNF 1.0 ISO-8859-1;
language en-US;
mode voice;
root $yesno;

$yesno = yes | no ;
```

The above ABNF file willl fail when being added to STT.

The problem comes from the documentation linter adding a space after the `#`.  Once you remove the space, `#ABNF 1.0 ISO-8859-1;` the grammar will work as intended.

The sample files provided [here](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-grammarExamples) are not affected by this problem, likely because they were not linted.

Similarly, the other example provided [here](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-grammarUnderstand#namesGrammar) also has the same problem.

**Comment by jeffpk62** [comment]
I published workarounds for the parsing issue and opened an issue against the build owners.  Thank you for identifying the problem!
