### ISSUE TITLE
About page not updated

### ISSUE THREAD

**Issue by francesca-gigante** [ibm-cloud-docs/speech-to-text#215]
Hi,
in the 'about' page, in the catalog, the supported languages list is not up-to-date (Italian, dutch and some others are missing)
https://cloud.ibm.com/catalog/services/speech-to-text#about

Regards
Francesca

**Comment by jeffpk62** [comment]
@francesca-gigante I'm not sure who maintains this page.  It's not something that I work with.  I can pass along this comment to the offering and release managers to make them aware.

**Comment by francesca-gigante** [comment]
@jeffpk62 thanks.

**Comment by jeffpk62** [comment]
@francesca-gigante I am now working with the offering team to update this information.  A few of us will address separately.  I am closing this public issue.  Thank you again for the notification!
