### ISSUE TITLE
Turkish language suuport

### ISSUE THREAD

**Issue by ali-saadat** [ibm-cloud-docs/speech-to-text#216]
Thank you for your contribution
I was wondering whether the solution supports the Turkish language or not?
I could not find any relative model at your website
https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-models#models

**Comment by jeffpk62** [comment]
@ali-saadat Sorry for the very late response.  No, Speech to Text has no Turkish language support, unfortunately.
