### ISSUE TITLE
Question about timestamp "padding"

### ISSUE THREAD

**Issue by jaxtastic** [ibm-cloud-docs/speech-to-text#223]
We are using the IBM speech-to-text service to obtain durations of words produced by stroke survivors, using the onset and offset timestamps. We have extensive experience reliably obtaining these measures manually by trained research assistants. On visual inspection of the timestamps, there appears to be some "padding" both on the onset and offset of about 45 msec. In other words, the word duration from the timestamps appears about 90 msec longer than a manual measurement would show. Does anybody know if there is some constant value of padding that is used in the timestamps or alternatively is there information available about how the timestamps are generated? Thank you in advance for any information you can provide!

Best, 

Adam Jacks, Ph.D., CCC-SLP
Associate Professor
Coordinator of Master’s Studies
Division of Speech and Hearing Sciences
Department of Allied Health Sciences
The University of North Carolina at Chapel Hill
adam_jacks@med.unc.edu
(919) 918-5928

**Comment by jeffpk62** [comment]
Good morning, @jaxtastic.  Here's the response I got from the development team:

> I do not think there is explicit padding, it might be related to the left and right context information that speech features carry. Practically speaking, if they see the "padding" and it is consistent, they can remove it if that gets them closer to the word.

So, no explicit padding, more just a small artifact of speech processing.  I hope that helps?
